### ISSUE TITLE
Do recursive scans

### ISSUE THREAD

**Issue by oekarlsson** [mittwald/kube-av#17]
**Is your feature request related to a problem? Please describe.**
It seems that clamscan is told not to do recursive scans of the scan targets. This should be default or at least be an option you can set somehow. I cannot find anywhere how to set this, but perhaps there is a way?

**Describe the solution you'd like**
I would like that the -r is added to the list of arguments when running clamscan to scan files in all subdirectoies.

**Describe alternatives you've considered**
Perhaps an option to be able to set that recursive scan should be done.

**Additional context**
I have been using the latest images available (alpha-14)

**Comment by martin-helmich** [comment]
Thanks for your feedback :+1: and full ACK from me -- I'd also expect recursive scanning to be the default. Fix incoming.
