### ISSUE TITLE
kube-av is not listed in Mittwald's helm chart.

### ISSUE THREAD

**Issue by Tom284** [mittwald/kube-av#9]
I followed the installation guide from the readme but the mittwald repo doesn't contain kube-av. When I use helm repo search mittwald it lists these:
```
mittwald/aptly
mittwald/brudi-operator 
mittwald/harbor-operator 
mittwald/kube-mail       
mittwald/kubernetes-replicator
mittwald/kubernetes-secret-generator   
mittwald/pypiserver               
mittwald/servicegateway    
```

Would it be possible for you to add kube-av to the mittwald repo?

**Comment by elenz97** [comment]
Hey @Tom284!

Thanks for your question.

I have to admit that in the "[Installation](https://github.com/mittwald/kube-av#installation)" section of our readme we've got a typo in the helm chart name (see https://github.com/mittwald/kube-av/pull/10).

You could also refer to the content of https://helm.mittwald.de/index.yaml in which `kubeav` should be listed.

As kubeav currently is currently tagged `alpha`, you need to specify `--devel` to include development versions or `--version` using a specific [version](https://github.com/mittwald/kube-av/releases) in your `helm install` command.

I was able to install a release via: 
```
helm install kubeav mittwald/kubeav --devel
```

HTH

**Comment by Tom284** [comment]
Thank you very much for answering my question! I was indeed able to deploy kube-av  using --devel.
